name: It Came From A Box
favicon: null
layout_spectrum: 1
typography_spectrum: 0.07272
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbb23c'
    - '#18162f'
    - '#00a159'
    - '#f4f6f8'
    - '#a27536'
  brandStrength: 0.03541288431733847
  lightness: 0.32214761851355433
  saturation: 0.2580307191237807
  rhythmicContrast: 0.29962962539866567
purpose: []
